version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DATABASES_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DATABASES_POSTGRES_PASSWORD}

  redis:
    image: redis

  nginx:
    build: ./nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - web

  celery:
    build: .
    command: celery -A djangodocker worker -l INFO
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis

  web:
    build: .
    command: gunicorn -c /code/djangodocker/gunicorn_config.py djangodocker.wsgi:application
    volumes:
      - .:/code
    expose:
      - ${DJANGO_PORT}
    depends_on:
      - db
      - redis
    env_file:
      - .env
