# Generated by Django 3.2.5 on 2021-07-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=10)),
                ('points', models.CharField(max_length=10)),
                ('wins', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('given_name', models.CharField(max_length=200)),
                ('family_name', models.CharField(max_length=200)),
                ('driver_number', models.CharField(max_length=10)),
            ],
        ),
    ]
