# Generated by Django 3.2.6 on 2021-08-04 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20210728_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='twitter_username',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DriverTwitterMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('followers_count', models.BigIntegerField()),
                ('following_count', models.BigIntegerField()),
                ('listed_count', models.BigIntegerField()),
                ('tweet_count', models.BigIntegerField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
    ]
